# NOT for production usage.
services:
  server:
    container_name: back-dev
    image: tnw-server-dev:latest
    build:
      context: .
      dockerfile: docker/development/Dockerfile
      tags:
        - tnw-server-dev:latest
    environment:
      NODE_ENV: development
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/node/app/src
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-tier

  database:
    container_name: postgres-dev
    restart: always
    image: postgres:16.9-bookworm
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    networks:
      - app-tier
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 5s


networks:
  app-tier: